# Generated by Django 2.0 on 2017-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
