# Generated by Django 2.0 on 2017-12-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20171204_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
