# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mako'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mako',
            name='author',
        ),
        migrations.DeleteModel(
            name='Mako',
        ),
    ]
